### PR TITLE
Data Integration

### PR DESCRIPTION
**Pull request by jakecobley**
**Description**  
Added `printData()` and `getData` functions. Grabs and prints data from the YAML files located in the `data` folder in the root. 

I've added a `global.yml` and a `blog-titles.yml` file with some variables/arrays to get us started.

Example usage below:

```
// Grabs the site name from the site name variable in the global.yml file in the data directory.
<?php printData('global', 'site-name'); ?>

// Grabs a random entry from the blog-titles object in the blog-titles.yml file in the data directory.
<?php printData('blog-titles'); ?>

// Grabs the second (starts from 0) blog title from the blog-title object in the blog-titles.yml file in the data directory.
<?php printData('blog-titles', 1); ?>

// Sets $someVariable equal to the site's email address from the site name variable in the global.yml file in the data directory.
<?php $someVariable = getData('global', 'email'); ?>

```

**Related Issue**  
#4

**How Has This Been Tested?**  
Tested both `printData()` and `getData` with and without the second parameter being specified.

**Types of changes**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/getchopchop/chopchop/blob/next/.github/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by daveredfern** [comment]
@jakecobley what's the ETA on the update? :)

Me and Gaz will start putting some other data files together based on the examples here.

**Comment by jakecobley** [comment]
I'll have it done this afternoon.

**Comment by jakecobley** [comment]
What I've done is "quick and dirty" just to get us going. I'm going to go over it later on to clean it up and add documentation and error states.

I've changed the format of the .yml files slightly.

With the new functions the following will work: (The getData works exactly the same it just doesn't print the information)

```
// Grabs the site name from the site name variable in the global.yml file in the data directory.
<?php printData('global', 'site-name'); ?>

// Grabs a random entry from the title object within the blog object in the blog.yml file in the data directory.
<?php printData('blog', 'title'); ?>

// Grabs the first (starts from 0) title from the title object within the blog object in the blog.yml file in the data directory.
<?php printData('blog', 'title' 0); ?>

// Grabs the second (starts from 0) author from the author object within the blog object in the blog.yml file in the data directory.
<?php printData('blog', 'author', 1); ?>

// Grabs the second (starts from 0) blog title from the blog-title object in the blog-titles.yml file in the data directory.
<?php printData('blog-title', 1); ?>

// Grabs a random entry from the blog-titles object in the blog-titles.yml file in the data directory.
<?php printData('blog-title'); ?>
```

@daveredfern is this everything you wanted?

**Comment by gazjoy** [comment]
@jakecobley you are my hero 😍

**Pull request merged**
