### PR TITLE
Updated build process (Gulp)

### PR DESCRIPTION
**Pull request by jakecobley**
Each build function can now be run on multiple sources, cleaned up the formatting, and split the task and path config out.

### CODE REVIEW

**Comment by daveredfern** [comment]
@jakecobley are all the commands still the same? these are just under the hood stuff?

**Comment by jakecobley** [comment]
None of NPM commands have changed. You still have the following:
```
npm run watch
npm run build
npm run build:production
```

**Comment by gazjoy** [comment]
@jakecobley there are a few things I have noticed that need changing before we can merge this.

1. you are using "vectors" instead of "vector" in the gulpfile. Everything from now on should be singular to avoid confusion.
2. When adding a new folder to the vector folder it doesn't get built. (It does in the current gulpfile).

**Comment by jakecobley** [comment]
The path object has changed to allow multiple sources, exclusions, and a third-party flag for all tasks. This allows vendor scripts and scripts from Bower/NPM modules to be minified etc.

See here:
```
"svgSprite":
    [
        {
            "src": "./src/img/vectors/general/**/*.svg",
            "dist": "./build/img/vectors/general/",
            "exclude": []
        },
        {
            "src": "./src/img/vectors/payments/**/*.svg",
            "dist": "./build/img/vectors/payments/",
            "exclude": []
        },
        {
            "src": "./src/img/vectors/social/**/*.svg",
            "dist": "./build/img/vectors/social/",
            "exclude": [],
        }
    ],
```

I've not had time to add the option to run on all files within a directory. Just committed a HACK to solve this until I have time to do it properly.

**Comment by gazjoy** [comment]
@jakecobley this works now thanks.

**Comment by gazjoy** [comment]
pasted_image
@jakecobley just found the watch task gives a fat error, can you fix as soon as possible? Hoping to get this into the next release, (before end of Feb).

**Comment by jakecobley** [comment]
Tonight. If not I'm in the office tomorrow anyway.

**Comment by jakecobley** [comment]
Patched in PR #191

**Pull request merged**
